# GitHub Actions workflow for Continuous Integration.
# This workflow will run on every pull request to ensure code quality.
name: Backend CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Run placeholder tests
      run: |
        echo "Running linting and unit tests for all services..."
        echo "CI check passed!"
